contact_links:
  - name: Join nf-core
    url: https://nf-co.re/join
    about: Please join the nf-core community here
  - name: "Slack #mtdmr channel"
    url: https://nfcore.slack.com/channels/mtdmr
    about: Discussion about the nf-core/mtdmr pipeline
